name:                babo
version:             0.1.0.0
github:              "githubuser/babo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/babo#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4
- prettyprinter >= 1.7.1
- split >= 0.2.3.4
- extra >= 1.7.0
- containers >= 0.6.5.1
- monad-gen >= 0.3.0.1
- logict >= 0.7.1.0
- mtl >= 2.2.2

library:
  source-dirs: src

executables:
  babo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - babo

tests:
  babo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - babo
